apiVersion: v1
kind: Service
metadata:
  name: {{ include "optimizor-ui.fullname" . }}
  labels:
    {{- include "optimizor-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: web-ui
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: envoy
  selector:
    {{- include "optimizor-ui.selectorLabels" . | nindent 4 }}
